base:
  random_state: 42
  log_level: INFO

generate_dataset:
  valid_ratio: 0.2
  feature_selection: null # set null for None in python

train:
  batch_size: 256
  unit: [16, 8]
  learning_rate: 0.00001
  n_epochs: 50
  save_path: 'model/model.pt'
  early_stop: 500

evaluate:
  metrics_save_path: report/metrics.json
  pred_save_path: report/pred.csv